version: '3'

services:
 web:
  network_mode: bridge
  container_name: testwebapp
  build:
   context: .
   dockerfile: Dockerfile
  volumes:
   - "c:/docker-test-0.0.1-SNAPSHOT_logs:/usr/local/tomcat/docker-test-0.0.1-SNAPSHOT/log/"
  ports:
   - "8080:8080"
  depends_on:
   - database
  links:
   - database
   
 database:
  image: postgres:12
  network_mode: bridge
  container_name: counterdb
  restart: unless-stopped
  volumes:
   - ./counterdb.sql:/docker-entrypoint-initdb.d/counterdb.sql
  expose:
   - 5432
  ports:
   - 5432:5432
  environment:
   - POSTGRES_USER=admin
   - POSTGRES_PASSWORD=111
   - POSTGRES_DB=testdb
   - PGDATA=/var/lib/postgresql/data