version: '3'

services:
 web:
  network_mode: bridge
  container_name: testwebapp
  build:
   context: .
   dockerfile: Dockerfile
  volumes:
   - "c:/docker-test-0.0.1-SNAPSHOT_logs:/usr/local/tomcat/docker-test-0.0.1-SNAPSHOT/log/"
  ports:
   - "8080:8080"
  depends_on:
   - database
  links:
   - database
   
 database:
  image: postgres:12
  network_mode: bridge
  container_name: counterdb
  restart: always
  volumes:
   - "c:/docker-test-0.0.1-SNAPSHOT_db:/var/lib/postgresql/data"
  expose:
   - 8081
  ports:
   - 8081:8081
  environment:
   - POSTGRES_USER=admin​
   - POSTGRES_PASSWORD=111
   - POSTGRES_DB=testdb
   - PGDATA=/var/lib/postgresql/data